services:
  dvwa:
    build: .
    image: ghcr.io/digininja/dvwa:latest
    container_name: dvwa-1
    pull_policy: always
    environment:
      - DB_SERVER=db
    depends_on:
      - db
    networks:
      - dvwa
    ports:
      - 80:80
    restart: unless-stopped

  db:
    image: docker.io/library/mariadb:10
    container_name: db-1
    environment:
      - MYSQL_ROOT_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    volumes:
      - dvwa:/var/lib/mysql
    networks:
      - dvwa
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    container_name: elasticsearch-1
    environment:
      - discovery.type=single-node          # Single-node mode
      - ES_JAVA_OPTS=-Xms512m -Xmx512m      # Inital heap size - Maximum heap size
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - dvwa
    ports:
      - 9200:9200
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.22
    container_name: kibana-1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - dvwa
    ports:
      - 8080:5601
    restart: unless-stopped

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.22
    container_name: logstash-1
    user: root
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - /var/lib/docker/containers/a5672aaa90c35a56a43ec22169cad5d900af91f70ddff444b900ea08b627d66c/a5672aaa90c35a56a43ec22169cad5d900af91f70ddff444b900ea08b627d66c-json.log:/var/lib/docker/containers/dvwa/access.log
    depends_on:
      - elasticsearch
    networks:
      - dvwa
    restart: unless-stopped

volumes:
  dvwa:
  esdata:

networks:
  dvwa:
