version: '3.7'

volumes:
  dvwa:
  esdata:
  logs:

networks:
  dvwa:

services:
  dvwa:
    build: .
    image: ghcr.io/digininja/dvwa:latest
    pull_policy: always
    environment:
      - DB_SERVER=db
    depends_on:
      - db
      - logstash
    networks:
      - dvwa
    ports:
      - 127.0.0.1:4280:80
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  db:
    image: docker.io/library/mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    volumes:
      - dvwa:/var/lib/mysql
    networks:
      - dvwa
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - dvwa
    ports:
      - 9200:9200
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - dvwa
    ports:
      - 5601:5601
    restart: unless-stopped

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.0
    user: root
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - /var/lib/docker/containers/91fe12718b0b2c004766fd3e427c69056ba7964fef6801e1168dac6a1569c814:/var/lib/docker/containers/91fe12718b0b2c004766fd3e427c69056ba7964fef6801e1168dac6a1569c814:ro
    environment:
      - LOGS_PATH=/var/lib/docker/containers/91fe12718b0b2c004766fd3e427c69056ba7964fef6801e1168dac6a1569c814/91fe12718b0b2c004766fd3e427c69056ba7964fef6801e1168dac6a1569c814-json.log
    depends_on:
      - elasticsearch
    networks:
      - dvwa
    restart: unless-stopped